apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawlerapibackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawlerapi
  template:
    metadata:
      labels:
        app: crawlerapi
    spec:
      containers:
        - name: crawlerapi
          image: heliofernandes/crawler_api
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80
---
apiVersion: v1
kind: Service
metadata:
  name: crawlerapi
spec:
  type: NodePort
  selector:
    app: crawlerapi
  ports:
    - port: 8080
      targetPort: 80

